stages:
  - build
  - deploy

build_image:
    stage: build
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    before_script:
        - docker login -u nexncommunication2022 -p Netcon@123 registry.gitlab.com
    script:
        - docker build -t registry.gitlab.com/netcon2/edgex-data/ .
        - docker push registry.gitlab.com/netcon2/edgex-data/
        